version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: forte-saver-db
    restart: unless-stopped
    environment:
      - POSTGRES_DB=forte_saver
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  forte-saver:
    build: .
    container_name: forte-saver
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - ALLOWED_USERS=${ALLOWED_USERS}
      - DATABASE_URL=jdbc:postgresql://postgres:5432/forte_saver?user=postgres&password=${POSTGRES_PASSWORD:-postgres}
    env_file:
      - .env

volumes:
  postgres_data:
